package com.esgc.Utulities;

import java.util.HashMap;
import java.util.Map;

public class EntityIssuerESGSubcategoriesDescriptions {


    public Map<String, String> getDescriptionMap() {
        return descriptionMap;
    }

    public Map<String, String> descriptionMap = new HashMap<String, String>() {{
       
        put("Business_Ethics", "In this sub-category, we assess an entity’s approach to ensuring that business ethics are upheld by its staff. We look at how the entity builds and maintains a risk culture to prevent corruption, conflicts of interests, money laundering, financing of terrorism, whistle-blower protection, including due diligence on suppliers and partners on corruption risks.");
        put("Competition", "In this sub-category, we assess an entity’s approach to preventing anti-competitive practices. This relates to compliance with competition laws, preventing market distortion rules, cartels and abuse of dominant market position, dumping and violation of industrial property, collaboration with regulators and monitoring agencies, whistle-blower protection.");
        put("Lobbying", "In this sub-category, we assess an entity’s approach to managing lobbying activities. This relates to transparency on topics of interest for the entity such as relations with public authorities and officials, lobbying activities and expenditures, integrity and transparency when performing lobbying activities.");
        put("Board", "In this sub-category, we assess the structure, composition and activities of the Board of Directors. Important elements are the composition of the Nomination Committee, the frequency of election of Board members, the independence of the Chairman and Board members, the diversity and competencies of the Board as well as procedures in place (training programs, regularity and attendance of meetings, assessment procedures). We also assess the Board’s accountability and responsibility for sustainability issues.");
        put("Stakeholder_Relations", "In this sub-category, we assess an entity’s approach to managing multi-stakeholder engagement. This refers to fair treatment of shareholders, rights of stakeholders and stakeholder interests, sustainability strategy design, and implementation.");
        put("Internal_Controls_and_Risk_Management", "In this sub-category, we assess an entity’s approach towards audit and internal controls as well as ESG/sustainability risk management. This covers the existence and functioning of the Audit Committee, the Committee members’ skills and background, the entity’s efficient identification and evaluation of risks, and the integration of sustainability into internal control and risk management systems.");
        put("Executive_Remuneration", "In this sub-category, we assess an entity’s approach to managing executive remuneration. This covers the existence and independence of a Remuneration Committee, the alignment of interests of executives with those of the organization and its shareholders, transparency on executive pay including short-term and long-term incentives and their link with sustainability targets, CEO-pay-ratio.");
        put("Cyber_and_Technological_Risks", "In this sub-category, we assess an entity’s approach to preparing for cyber and other types of technological risks that it may face, or may pose to its stakeholders. This includes ensuring data of employees and clients is safely stored and handled, and grant operations and services continuity. We also assess the entity’s data management and cybersecurity systems including risk management, training to employees, grievance mechanisms.");
        put("Supplier_Relations", "In this sub-category, we assess an entity’s approach to ensuring sustainable relations with suppliers. This refers to commitment and measures to ensure open dialogue with suppliers, joint development projects to ensure sustainable supplier relations.");
        put("Sustainable_Sourcing", "In this sub-category, we assess an entity’s approach to integrating ESG criteria into its supply chain management processes. This refers to the integration of ESG and integrity factors in supply chain management including contractual clauses, due diligence and corrective actions, engaging with suppliers and regular audits.");
        put("Labour_Rights_and_Relations", "In this sub-category, we assess an entity’s approach to managing social dialogue and respecting fundamental labor rights. This covers strategy and measures to promote collective bargaining and social dialogue forums, facilitate consultation and negotiating processes, and educate employees on the rights to collective bargaining and the right to unionize.");
        put("Reorganizations", "In this sub-category, we assess a company’s approach to managing workforce reorganizations. This covers informing and consulting employee representatives on restructurings matters, implementing measures to prevent and limit redundancies and/or the negative effects of redundancies, and promoting employment growth. These can be addressed through collective bargaining, collective information, and consultation.");
        put("Career_Development", "In this sub-category, we assess an entity’s approach to managing career development for its workforce. This includes transparent and individualized career development frameworks, commitments and efforts to ensure human capital formation, promoting employment opportunities, providing training and skill enhancement for employees including seniors.");
        put("Health_and_Safety", "In this sub-category, we assess an entity’s approach to managing the physical and mental wellbeing of its workforce. This refers to building a health and safety culture, continuously improvement of health and safety systems, prevention of accidents and occupational diseases. The entity also needs to adapt to remote working needs and respect the right to disconnect to minimize stress and mental health risks among employees.");
        put("Wages_and_Hours", "In this sub-category, we assess a company’s approach to managing wages and working hours for its workforce");
        put("Fundamental_Human_Rights", "In this sub-category, we assess an entity’s approach to ensuring the respect of human rights. This includes and is not limited to the right to privacy, personal security, property rights and right to land, right to be prevented from cruel, inhuman, or degrading treatment, complicity in human rights violation.");
        put("Diversity_and_Inclusion", "In this sub-category, we assess an entity’s approach to managing diversity and inclusion within its workforce. This includes non-discrimination against race, color, sex, religion, political opinion, national extraction or social origin, among others, reducing gender pay gaps, improving diversity and inclusion through monitoring and engaging with employees.");
        put("Modern_Slavery", "In this sub-category, we assess an entity’s approach to managing modern slavery. This refers to the commitment and measures to manage modern slavery risk and due diligence on human trafficking, debt bonded labor, child labor and forced labor. These measures can include complaint management, capacity building and audits.");
        put("Social_and_Economic_Development", "In this sub-category, we assess an entity’s approach to promoting social and economic development in the communities where it directly operates. This includes commitment and efforts to manage the impact of their operations on the local economy, promote local businesses and labor market, transfer technology and skills, promote, manage social impacts related to site closures and restructuring, and engage with local communities.");
        put("Societal_Impacts", "In this sub-category, we assess a company’s approach to managing the societal impacts of its products and services. We assess if the entity offers affordable products adapted to the ‘Bottom of the Pyramid’s needs, manage negative impacts through engaging with customers and other stakeholders.");
        put("Responsible_Tax", "In this sub-category, we assess a company’s approach to managing tax fairness and transparency. This refers to the entity’s contribution to the economic and social development of communities through tax payments to finance public services, public institutions, and services citizens need. We assess the entity’s tax strategies, tax compliance and reporting, controls and employee engagement.");
        put("Product_Safety", "In this sub-category, we assess an entity’s approach to managing product and service safety. This covers quality and safety management certification schemes, systems to prevent and alert product/service safety risks and post-crisis improvement plans.");
        put("Customer_Engagement", "In this sub-category, we assess an entity’s approach to managing marketing and customer engagement activities. This refers to ensuring customers’ right to be safe, right to be informed, right to choose and right to be heard through transparent and responsible marketing practices, customer satisfaction and complaint management.");
        put("Environmental_Protection", "In this sub-category, we assess an entity’s overarching approach towards environmental management and protection. This refers to an environmental strategy to address environmental impacts associated with business activities and operations, environmental management systems covering monitoring and reporting, risk identification and audits.");
        put("Transition_Risks", "In this sub-category, we assess an entity’s approach towards transitioning to a lower-carbon business model. This refers to the integration of transition risks into their business models, setting targets and measures to reduce greenhouse gas emissions (Scope 1, 2, and 3), energy use from primary sources (fossil fuels, nuclear, renewables) and secondary sources (electricity, steam, heat). Measures include carbon footprint assessment, renewable energy, energy and carbon audits, among others.");
        put("Physical_Risks", "In this sub-category, we assess an entity’s approach to managing the physical impacts of climate change on its business. Physical impacts of climate change can be effects of severe climatic events on raw materials’ availability, impacts of flooding on building and infrastructure designs. We assess the entity’s integration of these impacts into their business models, risk management and project development.");
        put("Biodiversity", "In this sub-category, we assess a company’s approach to managing its impact on biodiversity. This covers monitoring and assessing the impact of operations on biodiversity, putting in place measures and practices to reduce risks and disruptions to biodiversity.");
        put("Water_Management", "In this sub-category, we assess a company’s approach to managing water consumption and water emissions. This covers strategy and measures to reduce their water consumption, optimize water consumption and use by using water-saving technologies and recycling, as well as monitoring and reporting.");
        put("Air_Emissions", "In this sub-category, we assess a company’s approach to managing air emissions that are not linked to greenhouse gases. This refers to strategy and measures to reduce air emissions during the production process, along with monitoring and reporting.");
        put("Material_Flows", "In this sub-category, we assess a company’s approach to managing waste generation and management. Transitioning to a circular economy requires entities to increase efficiency in waste and materials management by reusing and recycling waste and residues, reducing the production of landfilled waste, together with monitoring and reporting.");

    }};
}
