package com.esgc.Tests.TestBases;

public class Descriptions {
    public static String OVERALL_ESG_SCORE = "The Overall ESG score allows users to quickly understand and compare the performance of an entity to the whole universe of entities assessed by this framework. Moody’s ESG Assessment Framework reflects a Double Materiality perspective of companies’ and organizations’ ESG performance. They measure the degree to which an entity manages its exposure to and management of Environmental, Social, and Governance (ESG) factors that are material to its stakeholders and business from both a risk mitigation and value creation perspective.";
    public static String MARKET_RISK_DESCRIPTION = "We evaluate each company’s Market Risk with two indicators. The Country of Sales indicator is a measure of climate risk in the countries in which a company generates its sales. The Weather Sensitivity indicator is an approximate measure of how weather variability has historically affected a company’s industry.";
    public static String SUPPLY_CHAIN_RISK_DESCRIPTION = "We evaluate Supply Chain Risk with two indicators. The Country of Origin indicator is a measure of climate risk in countries that export commodities that a company depends on for production and delivery of products and services. The Resource Demand indicator is a measure of the industry-level dependence on climate-sensitive resources such as water, land and energy across the supply chain. To attribute sector-level supply chain risk to companies, we leverage revenue segment reporting from companies’ financial statement disclosures and map it to sector codes on the same classification scheme, herein referred to as Company Sector Revenue.";
    public static String OPERATIONS_RISK_DESCRIPTION = "We score companies for Operations Risk by aggregating site-level climate hazard exposure across all of their known facilities, which can range from manufacturing sites and warehouses to offices and retail stores. We assess exposure to six climate hazards, including floods, heat stress, hurricanes & typhoons, sea level rise, water stress, and wildfires. The scoring process accounts for the fact that facilities will be affected differently by climate hazards based on their activities. For example, a manufacturing plant that has heavy water and energy inputs will be more sensitive to heat stress and water stress than an office in the same location.";
    public static String PHYSICAL_RISK_MANAGEMENT_DESCRIPTION = "We evaluate how companies are acting to anticipate, prevent and manage the risks associated with the physical impacts of climate change. The assessment is based on corporate disclosures related to physical risks identification and measures put in place to address exposure to physical risks.";
    public static String TEMPERATURE_ALIGNMENTS_DESCRIPTION = "Temperature Alignment is a forward-looking dataset of the alignment of companies’ decarbonization targets with carbon emissions trajectories. We compare company targets to decarbonization benchmarks derived from scenarios published by the International Energy Agency (IEA). For each company, we provide a Temperature Alignment assessment (implied temperature rise) which indicates the temperature outcome with which the company is considered aligned based on its pathway over the period to 2030 and/or to the target year set by the company. We also provide an alignment level on a four-level scale: Well Below 2°C, Below 2°C, 2°C, and Above 2°C.";
    public static String CARBON_FOOTPRINT_DESCRIPTION = "We evaluate a companies’ carbon footprint based on the direct (Scope 1) and indirect (Scope 2) emissions. When emissions data is not publicly disclosed, we estimate Scope 1 and Scope 2 emissions using our own proprietary models. Other indirect emissions (Scope 3), are also collected or estimated and provided but are not part of the carbon footprint grade.\n\nPortfolio securities that are not covered within the dataset are excluded from the weighted average calculations.";
    public static String ENERGY_TRANSITION_MANAGEMENT_DESCRIPTION = "We evaluate companies’ decarbonization efforts through a qualitative assessment of the commitments, policies, measures put in place and a trend analysis of sector relevant KPIs. The score is composed of three pillars: leadership (commitment, policies and targets), implementations (measures) and results (KPIs and controversies).";
    public static String BROWN_SHARE_ASSESSMENT_DESCRIPTION = "Brown Share Assessment contains a dedicated screening of companies’ involvement in various fossil fuel activities in terms of revenue, turnover and fossil fuel reserves data covering both conventional and unconventional resources.\n\nPortfolio securities that are not covered within the dataset are excluded from the weighted average calculations.";
    public static String TCFD_CLIMATE_STRATEGY_DESCRIPTION = "We assess the adoption and disclosure level of the TCFD recommendations. We have broken down the pillars of governance, strategy, and risk management into 27 indicators. For the purpose of scoring, these indicators were regrouped following our scoring framework into the leadership (governance), implementation (strategy and risk management) and results (controversies) pillars.";
    public static String GREEN_SHARE_ASSESSMENT_DESCRIPTION = "We identify companies’ involvement in products and services that contribute to the transition to a low carbon economy.\n\nPortfolio securities that are not covered within the dataset are excluded from the weighted average calculations.";
    public static String PHYSICAL_RISK_HAZARDS_DESCRIPTION = "We evaluate your portfolio’s percentage of corporate facilities exposed to high risk/red flag for the physical climate hazard that has the highest average score in your portfolio. We leverage the company’s Operations Risk to calculate your highest physical climate hazard exposure. We score companies for Operations Risk by aggregating site-level climate hazard exposure across all of their known facilities, which can range from manufacturing sites and warehouses to offices and retail stores. We assess exposure to six climate hazards, including floods, heat stress, hurricanes & typhoons, sea level rise, water stress, and wildfires.\n\nPortfolio securities that are not covered within the dataset are excluded from the weighted average calculations.";



    public static String OVERALL_ESG_SCORE_HEATMAP = "The Overall ESG score allows users to quickly understand and compare the performance of an entity to the whole universe of entities assessed by this framework. Moody’s ESG Assessment Framework reflects a Double Materiality perspective of companies’ and organizations’ ESG performance. They measure the degree to which an entity manages its exposure to and management of Environmental, Social, and Governance (ESG) factors that are material to its stakeholders and business from both a risk mitigation and value creation perspective.";
    public static String MARKET_RISK_DESCRIPTION_HEATMAP = "We evaluate each company’s Market Risk with two indicators. The Country of Sales indicator is a measure of climate risk in the countries in which a company generates its sales. The Weather Sensitivity indicator is an approximate measure of how weather variability has historically affected a company’s industry.";
    public static String SUPPLY_CHAIN_RISK_DESCRIPTION_HEATMAP = "We evaluate Supply Chain Risk with two indicators. The Country of Origin indicator is a measure of climate risk in countries that export commodities that a company depends on for production and delivery of products and services. The Resource Demand indicator is a measure of the industry-level dependence on climate-sensitive resources such as water, land and energy across the supply chain. To attribute sector-level supply chain risk to companies, we leverage revenue segment reporting from companies’ financial statement disclosures and map it to sector codes on the same classification scheme, herein referred to as Company Sector Revenue.";
    public static String OPERATIONS_RISK_DESCRIPTION_HEATMAP = "We score companies for Operations Risk by aggregating site-level climate hazard exposure across all of their known facilities, which can range from manufacturing sites and warehouses to offices and retail stores. We assess exposure to six climate hazards, including floods, heat stress, hurricanes & typhoons, sea level rise, water stress, and wildfires. The scoring process accounts for the fact that facilities will be affected differently by climate hazards based on their activities. For example, a manufacturing plant that has heavy water and energy inputs will be more sensitive to heat stress and water stress than an office in the same location.";
    public static String PHYSICAL_RISK_MANAGEMENT_DESCRIPTION_HEATMAP = "We evaluate how companies are acting to anticipate, prevent and manage the risks associated with the physical impacts of climate change. The assessment is based on corporate disclosures related to physical risks identification and measures put in place to address exposure to physical risks.";
    public static String TEMPERATURE_ALIGNMENTS_DESCRIPTION_HEATMAP = "Temperature Alignment is a forward-looking dataset of the alignment of companies’ decarbonization targets with carbon emissions trajectories. We compare company targets to decarbonization benchmarks derived from scenarios published by the International Energy Agency (IEA). For each company, we provide a Temperature Alignment assessment (implied temperature rise) which indicates the temperature outcome with which the company is considered aligned based on its pathway over the period to 2030 and/or to the target year set by the company. We also provide an alignment level on a four-level scale: Well Below 2°C, Below 2°C, 2°C, and Above 2°C.";
    public static String CARBON_FOOTPRINT_DESCRIPTION_HEATMAP = "We evaluate a companies’ carbon footprint based on the direct (Scope 1) and indirect (Scope 2) emissions. When emissions data is not publicly disclosed, we estimate Scope 1 and Scope 2 emissions using our own proprietary models. Other indirect emissions (Scope 3), are also collected or estimated and provided but are not part of the carbon footprint grade.";
    public static String ENERGY_TRANSITION_MANAGEMENT_DESCRIPTION_HEATMAP = "We evaluate companies’ decarbonization efforts through a qualitative assessment of the commitments, policies, measures put in place and a trend analysis of sector relevant KPIs. The score is composed of three pillars: leadership (commitment, policies and targets), implementations (measures) and results (KPIs and controversies).";
    public static String BROWN_SHARE_ASSESSMENT_DESCRIPTION_HEATMAP = "Brown Share Assessment contains a dedicated screening of companies’ involvement in various fossil fuel activities in terms of revenue, turnover and fossil fuel reserves data covering both conventional and unconventional resources.";
    public static String TCFD_CLIMATE_STRATEGY_DESCRIPTION_HEATMAP = "We assess the adoption and disclosure level of the TCFD recommendations. We have broken down the pillars of governance, strategy, and risk management into 27 indicators. For the purpose of scoring, these indicators were regrouped following our scoring framework into the leadership (governance), implementation (strategy and risk management) and results (controversies) pillars.";
    public static String GREEN_SHARE_ASSESSMENT_DESCRIPTION_HEATMAP = "We identify companies’ involvement in products and services that contribute to the transition to a low carbon economy.";
    public static String PHYSICAL_RISK_HAZARDS_DESCRIPTION_HEATMAP = "We evaluate your portfolio’s percentage of corporate facilities exposed to high risk/red flag for the physical climate hazard that has the highest average score in your portfolio. We leverage the company’s Operations Risk to calculate your highest physical climate hazard exposure. We score companies for Operations Risk by aggregating site-level climate hazard exposure across all of their known facilities, which can range from manufacturing sites and warehouses to offices and retail stores. We assess exposure to six climate hazards, including floods, heat stress, hurricanes & typhoons, sea level rise, water stress, and wildfires.\n\nPortfolio securities that are not covered within the dataset are excluded from the weighted average calculations";

}
