package com.esgc.Utilities;

public enum EntitlementsBundles {
    PHYSICAL_RISK,
    TRANSITION_RISK,
    CLIMATE_GOVERNANCE,
    PHYSICAL_RISK_TRANSITION_RISK,
    TRANSITION_RISK_CLIMATE_GOVERNANCE,
    PHYSICAL_RISK_CLIMATE_GOVERNANCE,
    USER_WITH_CONTROVERSIES_ENTITLEMENT,
    USER_WITH_OUT_CONTROVERSIES_ENTITLEMENT,
    USER_WITH_EXPORT_ENTITLEMENT,
    USER_WITH_OUT_EXPORT_ENTITLEMENT,
    USER_WITH_ESG_PS_ENTITLEMENT,
    USER_WITH_ESG_ENTITLEMENT,
    PDF_EXPORT_BUNDLE_ENTITLEMENT,
    PDF_EXPORT_ONLY_SOURCEDOCUMENTS_ENTITLEMENT,
    PDF_EXPORT_ONLY_PDF_ENTITLEMENT,

    ALL
}
