name: Remote Execution Test Demo

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: app-delivery-ec2-windows

    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: |
        mvn test -Phello -DfailIfNoTests=false -Dbrowser=chrome-remote -Denvironment=prod -Dfile.encoding=UTF8 -X
        
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1
