name: Selenium Tests on EC2

on:
  push:
    branches: [ users/devops/ec2runnertest ]

jobs:
  build:

    runs-on: app-delivery-ec2-windows

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        echo $MAVEN_HOME
        mvn --version
        mvn test -Dtest=PortfolioNameUpdateAPITest -DfailIfNoTests=false -Dbrowser=edge
    - name: Surefire Report
      uses: ScaCap/action-surefire-report@v1
